services:
  web_app:
    image: quizbot
    command: python fastapi_bot.py
    env_file:
      - .env
    environment:
      HOST: "0.0.0.0"
    ports:
      - "5000:5000"
  bot_ins_1:
    image: quizbot
    env_file:
      - .env
    environment:
      INSTANCE_INDEX: 0
      TOTAL_INSTANCES: 2
      TOTAL_SHARDS: 6

  bot_ins_2:
    image: quizbot
    env_file:
      - .env
    environment:
      INSTANCE_INDEX: 1
      TOTAL_INSTANCES: 2
      TOTAL_SHARDS: 6


networks:
  botnet:
    driver: bridge